<div id="featured-products_block_center" class="block products_block">
    <h4>Productos destacados</h4>
    <div class="block_content">
        <?php
        $params = array('slug'=>$this->slug);
        echo $paginator = $this->paginationControl($this->articulos,
                                    'Sliding',
                                    '/buscar/paginator.phtml',$params); 
        ?>
        <?php if(count($this->articulos)>0){?>
        <ul>
                        <?php foreach($this->articulos as $index): ?>
            <li class="ajax_block_product first_item clear ">
                <div id="product-box">
                    <h5>
                        <a href="#" title="<?php echo $index['nombre']?>"><?php echo $index['nombre']?></a>
                    </h5>
                    <div class="product_imagebox">
                        <a href="#" title="<?php echo $index['nombre']?>" class="product_image">
                            <img src="/imagen-articulo/<?php echo $index['imagen']?>" alt="<?php echo $index['nombre']?>" >
                        </a>
                    </div>
                    <div>
                        <p class="price_container" style="width: 100px; ">
                            <span class="price"><?php echo $index['precioventa']?></span>
                        </p>
                        <p class="price_container" style="width: 70px;">
                        <input type="text" style="width: 30px; height: 20px;">
                        <span>cantidad</span>
                        </p>
                        <p class="product_buttons">
                            
                            <a class="product-addcart ajax_add_to_cart_button" rel="ajax_id_product_14" href="" title="Añadir al carrito">Añadir al carrito</a>
                            <a class="product-viewdetails" href="/detalle-producto/<?php echo $index['idarticulo']?>" title="Ver">Ver</a>
                        </p>					
                    </div>						
                </div>
            </li>
            <?php  endforeach; ?>

        </ul>
        <?php echo $paginator;?>
    <?php  } else { ?>    
        No se encontro ningun articulo
    <?php  } ?>    
    </div>
</div>