<form action="<?php echo $this->element->getAction();?>" method="<?php echo $this->element->getMethod();?>">
<?php echo $this->element->codigo ?>
<?php echo $this->element->nombre ?>
<?php echo $this->element->descripcion ?>
<?php echo $this->element->precioventa ?>
<?php echo $this->element->preciocompra ?>
<?php echo $this->element->idcategoria ?>
<?php echo $this->element->Enviar ?>

</form>
   