<br />
<form action="<?php echo $this->element->getAction();?>" 
      method="<?php echo $this->element->getMethod();?>"
      enctype="<?php echo $this->element->getAttrib('enctype');?>">
    <div>

<?php echo $this->element->nombre ?>
<?php echo $this->element->descripcion ?>
<?php echo $this->element->link ?>
<?php echo $this->element->imagen ?>
<?php echo $this->element->estado ?>
<?php echo $this->element->Guardar ?>
    </div>
    <div>
<img src="/imagen-banner/<?php echo $this->element->getView()->imagen; ?>">
    </div>
</form>
   