
<form action="<?php echo $this->element->getAction();?>" 
      method="<?php echo $this->element->getMethod();?>"
      enctype="<?php echo $this->element->getAttrib('enctype');?>">
    <div>
        <table style="width: 600px;">
            <tr>
                <td >
                    <?php echo $this->element->idcategoria ?>
                </td>
                <td>
                    <?php echo $this->element->idcategoria2 ?>
                </td>
            </tr>
            <tr>
                <td >
                    <?php echo $this->element->idsubcategoria ?>
                </td>
                <td>
                    <?php echo $this->element->idsubcategoria2 ?>
                </td>
            </tr>
            <tr>
                <td >
                    <?php echo $this->element->idarticulo ?>
                </td>
                <td>
                    <?php echo $this->element->idarticulo2 ?>
                    <input type="button" value="Asignar" id="asignar" name="asignar" >
                    
                </td>
            </tr>
            <tr>
                <td colspan="2" >
                    <div id="error"></div>
                    <table id="listaAsignado" style="width: 300px;">
                        
                    </table>
                    
                </td>
            </tr>
     </table>
    </div>
    <?php echo $this->element->Enviar ?>
    
</form>
   