<div id="contenedor">
    	<div id="header">
        	<h1>Delivery Premiun Sac</h1>
            <h2>Actualiza tu explorador para una mejor experiencia </h2>
        </div>
        <div id="info">
	        <p>Recomendamos uno de los siguientes exploradores para entregarle la mejor 
                    y más confiable experiencia. 
                    Es posible que algunas funciones no tengan una funcionalidad 
                    completa en otros exploradores.</p>
        </div>
        <div id="navegadores">
        	<div class="browser_box">
            	<div class="browser_logo"><a href="https://www.google.com/chrome?hl=es" target="_blank"><img src="/f/img/browser_chrome.jpg" width="90" height="90" border="0" /></a></div>
                <div class="browser_content">
                	<h3>Google Chrome</h3>
                    <p>Disponible para Windows, Macintosh y Linux</p>
                    <p><a href="https://www.google.com/chrome?hl=es" target="_blank">Descargar desde Google</a></p>
                </div>
         	</div>
            <div class="browser_box">
            	<div class="browser_logo"><a href="http://www.mozilla.org/en-US/firefox/new/" target="_blank"><img src="/f/img/browser_firefox.jpg" width="90" height="90" border="0" /></a></div>
                <div class="browser_content">
                	<h3>Mozilla Firefox</h3>
                    <p>Disponible para Windows, Macintosh y Linux</p>
                    <p><a href="http://www.mozilla.org/en-US/firefox/new/" target="_blank">Descargar desde Mozilla</a></p>
                </div>	
            </div>
            <div class="browser_box">
            	<div class="browser_logo"><a href="http://www.apple.com/es/safari/" target="_blank"><img src="/f/img/browser_safari.jpg" width="90" height="90" border="0" /></a></div>
                <div class="browser_content">
                	<h3>Apple Safari</h3>
                    <p>Disponible para Windows y Macintosh</p>
                    <p><a href="http://www.apple.com/es/safari/" target="_blank">Descargar desde Apple</a></p>
                </div>	
            </div>
            <div class="browser_box">
            	<div class="browser_logo"><a href="http://windows.microsoft.com/es-ES/internet-explorer/products/ie/home" target="_blank"><img src="/f/img/browser_ie.jpg" width="90" height="90" border="0" /></a></div>
                <div class="browser_content">
                	<h3>Microsoft Internet Explorer 9</h3>
                    <p>Disponible para Windows</p>
                    <p><a href="http://windows.microsoft.com/es-ES/internet-explorer/products/ie/home" target="_blank">Descargar desde Microsoft</a></p>
                </div>	
            </div>
        </div>
    <div style="float: right; padding-top: 20px;"> 
        <script>(function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
            </script>
        <div class="fb-like-box" 
             data-href="http://www.facebook.com/deliverypremium" 
             data-width="480" 
             data-show-faces="true" 
             data-stream="true" 
             data-header="true"></div> 
    </div>
    </div>
