<div id="featured-products_block_center" class="block products_block">
    <h4>Productos destacados</h4>
    <div class="block_content">
        <?php
        $params = array('idsubcategoria' => $this->idsubcategoria);
        echo $paginator = $this->paginationControl($this->articulos, 'Sliding', '/productos/paginator.phtml', $params);
        ?>
        <?php if (count($this->articulos) > 0) { ?>
            <ul data-role="listview" data-inset="true" data-filter="false" data-divider-theme="d">
                <?php foreach ($this->articulos as $index): ?>
                    <li class="ajax_block_product first_item clear" role="option">
                        <div id="product-box">
                            <h5>
                                <a href="<?php echo $this->baseUrl(); ?>/detalle-producto/<?php echo $index['slug'] ?>" title="<?php echo $index['nombre'] ?>"><?php echo $index['nombre'] ?></a>
                            </h5>
                            <div class="product_imagebox">
                                <a href="<?php echo $this->baseUrl(); ?>/detalle-producto/<?php echo $index['slug'] ?>" title="<?php echo $index['nombre'] ?>" class="product_image">
                                    <img width="50" height="50" src="/imagen-articulo/<?php echo $index['imagen'] ?>?<?php echo rand(0,1000);?>" alt="<?php echo $index['nombre'] ?>" >
                                </a>
                            </div>
                            <div>
                                <form id="form_pres_<?php echo $index['idarticulo'] ?>" action="/realizar-pedido" method="Post">
                                    <input type="hidden" id="hidden_idArticulo_<?php echo $index['idarticulo'] ?>" name="producto" value="<?php echo $index['idarticulo'] ?>">
                                    <div class="price_container" style="width:110px;float:left; padding-left:10px;padding-top:10px">
                                        <?php if($index['flagoferta']==1){?>
                                        <div style="width: auto;" class="price-discount">Antes S/. <?php echo $index['precioventa'] ?></div>
                                        <div style="width: 120px; float: left; margin: 0px;" class="price">S/. <?php echo $index['preciooferta'] ?></div>
                                        <?php }else{?>
                                        <div style="width: 120px; float: left; margin: 0px;" class="price">S/. <?php echo $index['precioventa'] ?></div>
                                        <?php }?>
                                    </div>
								 </form>
                            </div>						
                        </div>
                    </li>
                <?php endforeach; ?>

            </ul>
            <?php echo $paginator; ?>
        <?php } else { ?>    
            No se encontro ningun articulo
        <?php } ?>    
    </div>
</div>