<div>
    <label>
        Buscar Cliente 
        <input type="text" name="searchCliente" id="searchCliente" >
    </label>
</div>
<div id="actionViewModal"> Nuevo Cliente </div>
    <span id="autocompleteCliente" style="position: absolute; background-color: #009ede;">
        
    </span>

<input type="hidden" value="" id="idcliente">
<div id="tableSeachCLiente"></div>
<div>
    <label>
        Buscar Articulo 
        <input type="text" name="searchArticulo" id="searchArticulo" >
    </label>
    <div id="tableSeachArticulo">
        
    </div>
    <span id="autocompleteArticulo" style="position: absolute; background-color: #009ede;">
        
    </span>
</div>
<table id="tableArticulo" class="sticky-enabled tableSelect-processed sticky-table">
    <thead class="tableHeader-processed">
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th>Total</th>
        </tr>
    </thead>
    
    <tbody>
        
    </tbody>
    
        <tr>
            <td> </td>
            <td> </td>
            <td> </td>
            <td style="color: red; font-weight: bold"> Total General </td>
            <td style="color: red; font-weight: bold"> <span id="total">0</span></td>
            <td> </td>
        </tr>

</table>

<div>
    <label>Fecha Entrega <input type="text"></label>
    <label>Hora Entrega </label>
    <select>
    <?php foreach(range(0,23) as $index): ?>
        <option value="<?php echo $index ?>"><?php echo strlen($index)==1?'0'.$index:$index;  ?>
        </option>
            <?php endforeach; ?>
        </select>
        <select>
            <option value="00">00</option>
            <option value="15">15</option>
            <option value="30">30</option>
            <option value="45">45</option>
        </select>
    
    
</div>
<div>
    <label> Informacion Adicional
    <textarea>

    </textarea>
        </label>
</div>
<div>
    <label>Responsable <input type="text" id="searchTextResponsable">
    <span id="responsableSearch" style="position: absolute; background-color: #009ede;"></span>
    <span id="responsable"></span>
    </label>
    
    
</div> 
<div> [<a href="#">Enviar Pedido</a>] - [<a href="">Cancelar Pedido</a>]</div>


<div id="modalView" class="modalInActive" >
    <div id="boxes" >
    <?php echo $this->formularioCliente ?>
    </div>    
</div>

<script type="text/javascript">
$(function() {
    $('#actionViewModal').click(function(){
        $("#modalView").attr('class','modalActive'); 
    });

    $("#searchTextResponsable").keypress(function(e) {
       if(e.which == 13){
           searchResponsable(this.value);
       } 
    });
    
    $( "#searchCliente" ).keypress(function(e) {
        if(e.which == 13){
            var valor = this.value;       
            $.ajax({
                data: "searchCliente="+valor,
                type: "POST",
                dataType: "json",
                url: "/admin/pedidos/ajax-search-clientes",
                success: function(data){ 
                    $('#autocompleteCliente').empty(); 
                    var contenido='';
                    contenido = '<div><table>';
                    for (var i = 0; i < data.length; i++) { 
                        contenido = contenido + '<tr style="cursor:pointer" name="asa" id="itemCliente-'+data[i]['idcliente']+'">';
                        contenido = contenido + '<td>';
                        contenido = contenido + data[i]['nombre'];
                        contenido = contenido + '</td>';
                        contenido = contenido + '<td>';
                        contenido = contenido + data[i]['apellidomaterno'] +' '+ data[i]['apellidopaterno'];
                        contenido = contenido + '</td>';
                        contenido = contenido + '</tr>';
                    }
                    contenido = contenido + '</table></div>';
                    $('#autocompleteCliente').append(contenido);
                    }
                    });
          }
      })
	

    $( "#searchArticulo" ).keypress(function(e) {
    
        if(e.which == 13){
            var valor = this.value;       
            $.ajax({
                data: "searchArticulo="+valor,
                type: "POST",
                dataType: "json",
                url: "/admin/pedidos/ajax-search-articulos",
                success: function(data){
                    $('#autocompleteArticulo').empty(); 
                    var contenido='';
                    contenido = '<div><table>';
                    for (var i = 0; i < data.length; i++) { 
                        contenido = contenido + '<tr style="cursor:pointer" id="itemArticulo-'+data[i]['idarticulo']+'">';
                        contenido = contenido + '<td>';
                        contenido = contenido + data[i]['nomArticulo'];
                        contenido = contenido + '</td>';
                        contenido = contenido + '</tr>';
                    }
                    contenido = contenido + '</table></div>';
                    $('#autocompleteArticulo').append(contenido);
                }
            });
        }
    })
        
        
        $("[id^=itemCliente]").live("click",function(){
        var idClienteArray = this.id.split('-');
        mostrarCLiente(idClienteArray[1]);
        });
        
        $("[id^=itemResponsable]").live("click",function(){
        var idClienteArray = this.id.split('-');
        mostrarResponsable(idClienteArray[1]);
        });
        
        $("[id^=itemArticulo]").live("click",function(){
        var idClienteArray = this.id.split('-');
        mostrarArticulo(idClienteArray[1]);
        });
        $("[id^=eliminarArti]").live("click",function(){
        var idArticuloArray = this.id.split('-');
        $(this).parent().parent().remove();
        eliminaArticulo(idArticuloArray[1]);
        totalProductos();
        });

    function mostrarResponsable(idusuario){
        $.ajax({
        data: "idusuario="+idusuario,
        type: "POST",
        dataType: "json",
        url: "/admin/pedidos/ajax-get-responsable",
        success: function(data){
                    var contenido='';
                        var nombre = data['apellidomaterno'];
                        nombre = nombre + ' ' + data['apellidopaterno'];
                        nombre = nombre + ' ' + data['nombre'];
                        contenido = nombre+'<input type="hidden" id="idusuario" value='+idusuario+'>';
            $('#responsable').empty(); 
            $('#responsableSearch').empty(); 
            $('#responsable').append(contenido);
            
            }
        });
    }
    function eliminaArticulo(idArticulo){
         $.ajax({
        data: "idArticulo="+idArticulo,
        type: "POST",
        dataType: "json",
        url: "/admin/pedidos/ajax-delete-articulo",
        success: function(data){
        }
         });
    }
    
    
    function mostrarArticulo(idArticulo){
        $.ajax({
        data: "idArticulo="+idArticulo,
        type: "POST",
        dataType: "json",
        url: "/admin/pedidos/ajax-get-articulo",
        success: function(data){
            var contenido='';
                contenido = contenido +'<tr id="row_'+data['idarticulo']+'">'
                contenido = contenido +'<td>'+data['nombre']+'<input type="hidden" name="idarticulo[]" value="'+data['idarticulo']+'" id="idarticulo_'+data['idarticulo']+'"></td>'
                contenido = contenido +'<td>'+data['descripcion']+'</td>'
                contenido = contenido +'<td><input name="precio[]" id="precio_'+data['idarticulo']+'" type="text" value="'+parseFloat(data['precioventa'])+'"></td>'
                contenido = contenido +'<td><input name="cantidad[]" id="cantidad_'+data['idarticulo']+'" type="text" value="1"></td>'
                contenido = contenido +'<td><input name="total[]" id="total_'+data['idarticulo']+'"  disabled="disabled" type="text" value="0"></td>'
                contenido = contenido +'<td>[<a id="eliminarArti-'+data['idarticulo']+'" href="#">Eliminar</a>]</td>'
                contenido = contenido +'</tr>'
            $('#tableArticulo tr:first').after(contenido);
            $('#autocompleteArticulo').empty(); 
            totalItem(data['idarticulo']);
            //totalProductos();
            }
        });
        }
        
        $("[id^=precio_]").live("keyup",function(e){
        var splitId = this.id.split('_');
        totalItem(splitId[1]);
        });
        $("[id^=cantidad_]").live("keyup",function(e){
        var splitId = this.id.split('_');
        totalItem(splitId[1]);
        });
        
        function totalProductos(){
            var total =0;
            $("[id^=idarticulo_]").each(function(){
                var splitId = this.id.split('_');
                total = total + parseFloat($('#total_'+splitId[1]).attr('value'));
            });
            $('#total').empty(); 
            $('#total').append(total);

        }
        
        function totalItem(idArticulo){
        $('#total_'+idArticulo).attr('value',parseFloat($('#precio_'+idArticulo).attr('value'))*parseFloat($('#cantidad_'+idArticulo).attr('value')));
        totalProductos();
        }
        
        
        function searchResponsable(textSearch){
        $.ajax({
        data: "buscarResponsable="+textSearch,
        type: "POST",
        dataType: "json",
        url: "/admin/pedidos/ajax-search-responsable",
        success: function(data){
                    var contenido='';
                    contenido = '<div><table>';
                    for (var i = 0; i < data.length; i++) { 
                        var nombre = data[i]['apellidomaterno'];
                        nombre = nombre + ' ' + data[i]['apellidopaterno'];
                        nombre = nombre + ' ' + data[i]['nombre'];
                        contenido = contenido + '<tr style="cursor:pointer" name="asa" id="itemResponsable-'+data[i]['idusuario']+'">';
                        contenido = contenido + '<td>';
                        contenido = contenido + nombre;
                        contenido = contenido + '</td>';
                        contenido = contenido + '</tr>';
                    }
                    contenido = contenido + '</table></div>';
            $('#responsableSearch').empty(); 
            $('#responsableSearch').append(contenido);
        }
        });
        
        }
        
        function mostrarCLiente(idCliente){
        $.ajax({
        data: "idCliente="+idCliente,
        type: "POST",
        dataType: "json",
        url: "/admin/pedidos/ajax-get-cliente",
        success: function(data){
            $('#tableSeachCLiente').empty(); 
            $('#idcliente').attr('value',data['idcliente']); 
            var contenido='';
            contenido = '<table class="sticky-enabled tableSelect-processed sticky-table">';
            contenido = contenido +'<thead class="tableHeader-processed">';
            contenido = contenido +'<tr>';
            contenido = contenido +'<th>Nombre</th>';
            contenido = contenido +'<th>Apellidos</th>';
            contenido = contenido +'<th>Ruc</th>';
            contenido = contenido +'<th>Dirección</th>';
            contenido = contenido +'<th>Telefonos</th>';
            contenido = contenido +'<th>Dni</th>';
            contenido = contenido +'</tr>';
            contenido = contenido +'</thead>';
            contenido = contenido +'<tbody>';
            contenido = contenido +'<tr>';
            contenido = contenido +'<td>'+data['nombre']+'</td>';
            contenido = contenido +'<td>'+data['apellidomaterno']+ ' ' +data['apellidopaterno']+'</td>';
            contenido = contenido +'<td>'+data['ruc']+ '</td>';
            contenido = contenido +'<td>'+data['direccion']+ '</td>';
            contenido = contenido +'<td>'+data['telefono1']+ ' - ' +data['telefono2']+ ' - ' +data['movil']+'</td>';
            contenido = contenido +'<td>'+data['dni']+ '</td>';
            contenido = contenido +'</tr>';
            contenido = contenido +'</tbody>';
            contenido = contenido + '</table>';
            $('#tableSeachCLiente').append(contenido);
            $('#autocompleteCliente').empty(); 
        }
        });
        
        }
        
         });

        
	</script>