<div>
    <label>Buscar Cliente <input type="text" name="searchCliente" id="searchCliente" ></label>
    <span id="autocompleteCliente" style="position: absolute; background-color: #009ede;"></span>
    [<a href="#">Nuevo Cliente</a>]
</div>
<table class="sticky-enabled tableSelect-processed sticky-table">
    <thead class="tableHeader-processed">
    <tr>
        <th>Nombre</th>
        <th>Apellidos</th>
        <th>Edad</th>
        <th>Dirección</th>
        <th>Telefonos</th>
        <th>Dni</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>Nazart</td>     
            <td>Jara Huaman</td>     
            <td>26</td>     
            <td>av. cueva pueblo - libre</td>     
            <td>2355168 - 989044605</td>     
            <td>44513555</td>     
        </tr>
    </tbody>
</table>
<div><label>Buscar Articulo <input type="text" name="searchArticulo" id="searchArticulo" ></label>
<span id="autocompleteArticulo" style="position: absolute; background-color: #009ede;"></span>
</div>
<table class="sticky-enabled tableSelect-processed sticky-table">
    <thead class="tableHeader-processed">
    <tr>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Precio</th>
        <th>Cantidad</th>
        <th>Total</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>articulo 1</td>
            <td>descripcion articulo 1</td>
            <td><input type="text" value="123"></td>
            <td><input type="text" value="2"></td>
            <td><input disabled="disabled" type="text" value="256"></td>
            <td>
                [<a href="">Eliminar</a>]
            </td>
        </tr>
        <tr>
            <td>articulo 1</td>
            <td>descripcion articulo 1</td>
            <td><input type="text" value="123"></td>
            <td><input type="text" value="2"></td>
            <td><input disabled="disabled" type="text" value="256"></td>
            <td>
                [<a href="">Eliminar</a>]
            </td>
        </tr>
        <tr>
            <td>articulo 1</td>
            <td>descripcion articulo 1</td>
            <td><input type="text" value="123"></td>
            <td><input type="text" value="2"></td>
            <td><input disabled="disabled" type="text" value="256"></td>
            <td>
                [<a href="">Eliminar</a>]
            </td>
        </tr>
        <tr>
            <td> </td>
            <td> </td>
            <td> </td>
            <td style="color: red; font-weight: bold"> Total General </td>
            <td style="color: red; font-weight: bold"> 738</td>
            <td> </td>
        </tr>
    </tbody>
</table>

<div>
    <label>Fecha Entrega <input type="text"></label>
    <label>Hora Entrega </label>
        <select>
            <?php
            foreach(range(0,23) as $index): ?>
            <option value="<?php echo $index ?>"><?php echo strlen($index)==1?'0'.$index:$index;  ?></option>
            <?php endforeach; ?>
        </select>
        <select>
            <option value="00">00</option>
            <option value="15">15</option>
            <option value="30">30</option>
            <option value="45">45</option>
        </select>
    
</div>
<div>
    <label> Informacion Adicional
    <textarea>

    </textarea>
        </label>
</div>
<div>
    <label>Responsable <input type="text"></label>    
    <span> Marcelo Carranza <a href="#">x</a></span> 
</div> 
<div> [<a href="#">Enviar Pedido</a>] - [<a href="">Cancelar Pedido</a>]</div>


<div id="basic-modal-content">
    <?php echo $this->formularioCliente ?>
</div>

<script type="text/javascript">
$(function() {
		$( "#searchCliente" ).bind( "keydown", function( ) {
                    var valor = this.value;
                                    $.ajax({
        data: "searchCliente="+valor,
        type: "POST",
        dataType: "json",
        url: "/admin/pedidos/ajax-search-clientes",
        success: function(data){ 
            $('#autocompleteCliente').empty(); 
            var contenido='';
            contenido = '<div><table>';
            for (var i = 0; i < data.length; i++) { 
                contenido = contenido + '<tr style="cursor:pointer" class="item-'+data[i]['nombre']+'">';
                contenido = contenido + '<td>';
                contenido = contenido + data[i]['nombre'];
                contenido = contenido + '</td>';
                contenido = contenido + '<td>';
                contenido = contenido + data[i]['apellidomaterno'] +' '+ data[i]['apellidopaterno'];
                contenido = contenido + '</td>';
                contenido = contenido + '</tr>';
                
            }
            contenido = contenido + '</table></div>';
            
            $('#autocompleteCliente').append(contenido);
        }
       });
			})
	});
        
$(function() {
$( "#searchArticulo" ).keypress(function(e) {
    $.ajax({
        data: "searchArticulo="+valor,
        type: "POST",
        dataType: "json",
        url: "/admin/pedidos/ajax-search-articulos",
        success: function(data){
            $('#autocompleteArticulo').empty(); 
            var contenido='';
            contenido = '<div><table>';
            for (var i = 0; i < data.length; i++) { 
                contenido = contenido + '<tr style="cursor:pointer" class="item-'+data[i]['nombre']+'">';
                contenido = contenido + '<td>';
                contenido = contenido + data[i]['nombre'];
                contenido = contenido + '</td>';
                contenido = contenido + '</tr>';
            }
            contenido = contenido + '</table></div>';
            $('#autocompleteArticulo').append(contenido);
        }
       });
			})
	});
        
        
        
        
        $("[class^=item]").bind("click",function(){
        alert('as');
        });
        
	</script>