<div id="bread-wrap">
    <div class="breadcrumb">
        <a title="volver a Inicio" href="/">Inicio</a>
        <span class="navigation-pipe">&gt;</span>
        <span class="navigation_page">Su carrito</span>
    </div>
</div>

<h1 id="cart_title">Paso (1) Resumen de su carrito</h1>
<div>&nbsp;</div>

<?php
if (count($this->listaArticuloCarrito) > 0) {
    $total = 0;
    ?>
    <p class="cart_shop">Su carrito contiene <span id="summary_products_quantity"><?php echo count($this->listaArticuloCarrito) ?> productos</span></p>
    <div>&nbsp;</div>
    <div class="table_block" id="order-detail-content">
        <table class="std" id="cart_summary">
            <thead>
                <tr>
                    <th class="cart_product first_item">Producto</th>
                    <th class="cart_description item">Nombre &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                    <th class="cart_availability item">P. Oferta</th>
                    <th class="cart_unit item">P. unitario</th>
                    <th class="cart_quantity item">Cantidad</th>
                    <th class="cart_total last_item">Total</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->listaArticuloCarrito as $index) {
                    $flagOferta = 0;
                    if($index['preciooferta']!=''&&$index['flagoferta']){
                        $flagOferta = 1;
                    }
                    ?>
                    <tr class=" cart_item" id="product_<?php echo $index['idarticulo'] ?>">
                        <td class="cart_product">
                            <a href="/detalle-producto/<?php echo $index['idarticulo'] ?>">
                                <img alt="<?php echo $index['nombre'] ?>" src="/imagen-articulo/<?php echo $index['imagen'] ?>"></a>
                        </td>
                        <td class="cart_description">
                            <a href="/detalle-producto/<?php echo $index['idarticulo'] ?>"><?php echo $index['nombre'] ?></a>	
                        </td>

                        <td class="cart_availability">
                            <span id="product_price_32_62" class="price">
                                S/. <?php echo $flagOferta?$index['preciooferta']:'0'; ?>		
                            </span>
                        </td>
                        <td class="cart_unit">
                            <span id="product_price_32_62" class="price <?php echo $flagOferta?'price-discount':'' ?>">
                                S/. <?php echo $index['precioventa'] ?>		
                            </span>
                        </td>
                        <td class="cart_quantity">
                            <div>
                                <a title="Eliminar" href="/realizar-pedido/eliminar-carrito/idArticulo/<?php echo $index['idarticulo'] ?>" id="32_62" 
                                   class="cart_quantity_delete" 
                                   rel="nofollow">
                                    <img height="13" width="11" class="icon" alt="Eliminar" 
                                         src="/f/img/icon/delete.gif"></a>
                            </div>
                            <div style="float:left;" id="cart_quantity_button">
                                <a title="Añadir" href="/realizar-pedido/add-cant/idArticulo/<?php echo $index['idarticulo'] ?>" id="cart_quantity_up_32_62" class="cart_quantity_up" rel="nofollow">
                                    <img height="9" width="14" alt="Añadir" src="/f/img/icon/quantity_up.gif">
                                </a>
                                <br>
                                <a title="sustraer" href="/realizar-pedido/restar-cant/idArticulo/<?php echo $index['idarticulo'] ?>" id="cart_quantity_down_32_62" class="cart_quantity_down" rel="nofollow">
                                    <img height="9" width="14" alt="sustraer" src="/f/img/icon/quantity_down.gif">
                                </a>
                            </div>
                            <input type="hidden" name="quantity_32_62_hidden" value="2">
                            <input type="text" name="quantity_32_62" value="<?php echo $index['cantidadArticulo'] ?>" 
                                   class="cart_quantity_input" size="2">

                        </td>
                        <td class="cart_total">
                            <span id="total_product_price_32_62" class="price">
                                S/.  <?php echo $flagOferta==1?$index['preciooferta'] * $index['cantidadArticulo']:$index['precioventa'] * $index['cantidadArticulo'] ?></span>
                        </td>
                    </tr>
                    <?php
                    if ($flagOferta) {
                        $total = $total + $index['preciooferta'] * $index['cantidadArticulo'];
                        } else {
                        $total = $total + $index['precioventa'] * $index['cantidadArticulo'];    
                    }
                }
                ?>
            </tbody>

            <tfoot>
                <tr class="cart_total_price">
                    <td colspan="5">Total productos:</td>
                    <td id="total_product" class="price" >S/. <?php echo $total; ?></td>
                </tr>
                <tr class="cart_total_price">
                    <td colspan="5">Precio Envío:</td>
                    <td id="total_price_without_tax" class="price">S/. 6.00</td>
                </tr>
                <tr class="cart_total_price">
                    <td colspan="5">Total:</td>
                    <td id="total_price" class="price">S/. <?php echo $total+6; ?></td>
                </tr>
            </tfoot>


        </table>
    </div>
    <p class="cart_navigation">
        <a title="Volver" class="button_extralarge" href="/realizar-pedido/registrar-pedido">
            Registrar la comprar
        </a>
        <a title="Siguiente" class="button_medium" 
           href="<?php echo $_SERVER['HTTP_REFERER'] ?>">Volver
        </a>
    </p>

<?php } else { ?>
    <p class="warning">Su carrito está vacío</p>
<?php } ?>