     <div id="maq_alineacion2">
            <div id="maq_principal">
                <div class="web_home">
                    <div id="web_columna1">
                        <div id="web_zonas">
                            <div class="zona">
                            	<table class="tablaZona" cellspacing="0">
                                	<tr>
                                    	<td class="td1">
                                        	<h3 class="subtitulo1">Enlaces <br />Descatados</h3>
                                            <p class="texto4">Los cursos de inglés general están diseñados
Los cursos de inglés general están diseñados
Los cursos de inglés general están diseñados</p>
                                        </td>
                                    </tr>
                                    <tr>
                                    	<td class="td2"><p class="texto2"><a href="#">Ver más</a></p></td>
                                    </tr>
                                </table>
                            </div>
                            <div class="zona">
                            	<table class="tablaZona" cellspacing="0">
                                	<tr>
                                    	<td class="td1">
                                        	<h3 class="subtitulo1">Enlaces <br />Descatados</h3>
                                            <p class="texto4">Los cursos de inglés general están diseñados
Los cursos de inglés general están diseñados
Los cursos de inglés general están diseñados</p>
                                        </td>
                                    </tr>
                                    <tr>
                                    	<td class="td2"><p class="texto2"><a href="#">Ver más</a></p></td>
                                    </tr>
                                </table>
                            </div>
                            <div class="zona">
                            	<table class="tablaZona" cellspacing="0">
                                	<tr>
                                    	<td class="td1">
                                        	<h3 class="subtitulo1">Enlaces <br />Descatados</h3>
                                            <p class="texto4">Los cursos de inglés general están diseñados
Los cursos de inglés general están diseñados
Los cursos de inglés general están diseñados</p>
                                        </td>
                                    </tr>
                                    <tr>
                                    	<td class="td2"><p class="texto2"><a href="#">Ver más</a></p></td>
                                    </tr>
                                </table>
                            </div><br />
                        </div>
                        <div id="web_extra"></div>
                    </div>
                </div>
            </div>
        </div>
        