<!-- Breadcrumb -->    
<div id="bread-wrap">
    <div class="breadcrumb">
        <a title="volver a Inicio" href="http://www.floreriadetalles.com/tienda/">Inicio</a>
        <span class="navigation-pipe">&gt;</span>
        <span class="navigation_page">Contacto</span>
    </div>
</div>

<!-- /Breadcrumb -->
<h1>Contacto</h1>
<p>Si desea información o contactarnos el primer paso es llenar el formulario que figura abajo
    o escribirnos a: <a href="mailto:pedidos@deliveripremiumsac.com">pedidos@deliveripremiumsac.com</a></p>

<?php echo $this->formContacto; ?>



