<form action="<?php echo $this->element->getAction();?>" method="<?php echo $this->element->getMethod();?>">
<?php echo $this->element->apellidomaterno ?>
<?php echo $this->element->apellidopaterno ?>
<?php echo $this->element->nombre ?>
<?php echo $this->element->direccion ?>
<?php echo $this->element->dni ?>
<?php echo $this->element->correo ?>
<?php echo $this->element->telefono1 ?>
<?php echo $this->element->ruc ?>
<?php echo $this->element->Enviar ?>
</form>
   