<?php if(is_array($this->messages) && count($this->messages)>0 ) { ?>
<div class="ybox center ">
	        <?php foreach($this->messages as $index):?>
	        <p><?php echo $index; ?></p>
                <?php endforeach;?>
        
    </div>
<?php } ?>
<?php echo $this->form; ?>

<table class="sticky-enabled tableSelect-processed sticky-table">
	<thead class="tableHeader-processed">
		<tr>
                    <th>Categoria</th>
                    <th>Descripción</th>
                    <th>Acciones</th>
		</tr>
	</thead>
	<tbody>
	<?php $i = 0;?>
	<?php if(count($this->paginator)>0):?>
	<?php foreach($this->paginator as $item):?>
            <?php $id = $item["idcategoria"]; ?>
		<tr class="<?php echo ($i%2==0)?"odd":"even";?>">			
			<td>
                            <span class="thmr_call"><?php echo $item["padre"];?>
                            </span>				
			</td>
			<td>
                            <span class="thmr_call"><?php echo $item["descripcion"];?>
                            </span>				
			</td>
			<td>
                            <?php $link = $this->url(array('action'=>'index','id'=>$id)) ?>
                            <a href="<?php echo $link; ?>">Modificar</a>
                            <?php $link = $this->url(array('action'=>'eliminar','id'=>$id)) ?>
                            <a href="<?php echo $link; ?>" onclick="return confirm('¿Estás seguro?')">Eliminar</a>
			</td>
		</tr>
	<?php $i++;?>	
	<?php endforeach;?>
	<?php else:?>
		<tr class="odd">
			<td colspan="2">No hay items disponibles.</td>	
		</tr>
	<?php endif;?>	
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    '/categoria/paginator.phtml'); ?>


