<?php $filter = new ZExtraLib_SeoUrl();
?>
    <!-- Breadcrumb -->
    <div id="bread-wrap">
        <div class="breadcrumb">
            <a title="volver a Inicio" href="<?php echo $this->baseUrl(); ?>">
                Inicio
            </a>
            <span class="navigation-pipe">&gt;</span>
            <span class="last-crumb">
                <?php if($this->categoria!='') {
                    if($this->idpadre){
                    ?>
                <a title="<?php echo $this->categoria['nombre']; ?>" href="<?php echo $this->baseUrl()?>/productos/<?php echo $filter->filter(trim($this->categoria['nombre']), '-', 0).'-'.$this->categoria['idcategoria']?>">
                    <?php echo $this->categoria['nombre']; ?>
                </a>
                
                <span class="navigation-pipe">&gt;</span>
                <?php } else { ?>
                <?php echo $this->categoria['nombre']; ?>
                <?php } 
                
                }?>
                
                <?php if($this->subCategoria!='') {?>
                    <?php echo $this->subCategoria['nombre']; ?>
                <?php } ?>
                
            </span>
        </div>
    </div>
    <!-- /Breadcrumb -->

<div id="featured-products_block_center" class="block products_block">
    <h4>Productos destacados</h4>
    <div class="block_content">
        <?php
        $params = array('idsubcategoria' => $this->idsubcategoria);
        echo $paginator = $this->paginationControl($this->articulos, 'Sliding', '/productos/paginator.phtml', $params);
        ?>
        <?php if (count($this->articulos) > 0) { ?>
            <ul>
                <?php foreach ($this->articulos as $index): ?>
                    <li class="ajax_block_product first_item clear ">
                        <div id="product-box">
                            <h5>
                                <a href="<?php echo $this->baseUrl(); ?>/detalle-producto/<?php echo $index['slug'] ?>" title="<?php echo $index['nombre'] ?>"><?php echo $index['nombre'] ?></a>
                            </h5>
                            <div class="product_imagebox">
                                <a href="<?php echo $this->baseUrl(); ?>/detalle-producto/<?php echo $index['slug'] ?>" title="<?php echo $index['nombre'] ?>" class="product_image">
                                    <img src="/imagen-articulo/<?php echo $index['imagen'] ?>" alt="<?php echo $index['nombre'] ?>" >
                                </a>
                            </div>
                            <div>
                                <form id="form_pres_<?php echo $index['idarticulo'] ?>" action="<?php echo $this->baseUrl();?>/realizar-pedido" method="Post">
                                    <input type="hidden" id="hidden_idArticulo_<?php echo $index['idarticulo'] ?>" name="producto" value="<?php echo $index['idarticulo'] ?>">
                                    <div class="price_container" style="width:110px;float:left; padding-left:10px;padding-top:10px">
                                        <?php if($index['flagoferta']==1){?>
                                        <div style="width: auto;" class="price-discount">Antes S/. <?php echo $index['precioventa'] ?></div>
                                        <div style="width: 120px; float: left; margin: 0px;" class="price">S/. <?php echo $index['preciooferta'] ?></div>
                                        <?php }else{?>
                                        <div style="width: 120px; float: left; margin: 0px;" class="price">S/. <?php echo $index['precioventa'] ?></div>
                                        <?php }?>
                                        
                                    </div>
                                    <p class="price_container" style="width: 50px;">
                                                                                <select id="text_cant_<?php echo $index['idarticulo'] ?>" 
                                            name="cantidad" >
                                            <?php for ($i=1;$i<=20;$i++) { ?>
                                            <option value="<?php echo $i; ?>">    
                                                <?php echo $i;?>
                                            </option>
                                            <?php } ?>
                                        </select>
                                        <span>cantidad</span>

<!--                                        <input type="text" id="text_cant_<?php echo $index['idarticulo'] ?>" name="cantidad" value="1" style="width: 30px; height: 20px;">
                                        <span>cantidad</span>-->
                                    </p>

                                    <p class="product_buttons">
                                        <a href="#" class="product-addcart ajax_add_to_cart_button" id="ajax_id_product_<?php echo $index['idarticulo'] ?>" rel="ajax_id_product_<?php echo $index['idarticulo'] ?>"  title="Añadir al carrito">
                                            Añadir al carrito
                                        </a>
                                        <a class="product-viewdetails" href="<?php echo $this->baseUrl();?>/detalle-producto/<?php echo $index['slug'] ?>" title="Ver">
                                            Ver
                                        </a>
                                    </p>
                                </form>
                            </div>						
                        </div>
                    </li>
                <?php endforeach; ?>

            </ul>
            <?php echo $paginator; ?>
        <?php } else { ?>    
            No se encontro ningun articulo
        <?php } ?>    
    </div>
</div>

<script type="text/javascript">

    $(function() {
        $("[id^=ajax_id_product_]").click(function(e){
            e.preventDefault();
            var Array = this.id.split('_');
            $("#form_pres_"+Array[3]).submit();
        }) 
        
    
        
    $("[id^=text_cant_]").keypress(function(e) {
        if(e.which == 13){
            e.preventDefault();
            var Array = this.id.split('_');
            $("#form_pres_"+Array[2]).submit();
        } 
    });    
});
</script>