<div id="bread-wrap">
    <div class="breadcrumb">
        <a title="volver a Inicio" href="/">Inicio</a>
        <span class="navigation-pipe">&gt;</span>
        <span class="navigation_page">Login</span>
    </div>
</div>
<form action="/login" method="post" class="formLoginClient">
    <table >
        <tr>
            <td>Usuario &nbsp;&nbsp;</td>
            <td><input type="text" name="login" id="login"></td>
        </tr>
        <tr>
            <td>Password &nbsp;&nbsp;</td>
            <td><input type="text" name="password" id="password"></td>
            <td>
                <input type="submit" value="Ok">
            </td>
        </tr>
    </table>
</form>