<?php
echo $this->message;
echo $this->form;
?>

<table class="sticky-enabled tableSelect-processed sticky-table">
	<thead class="tableHeader-processed">
		<tr>		
			<th>Tipo Documento</th>
			<th>Serie</th>
			<th>Desde</th>
                        <th>hasta</th>
		</tr>
	</thead>
	<tbody>
	<?php $i = 0;?>
	<?php if(count($this->paginator)>0):?>
	<?php foreach($this->paginator as $comprob):?>
		<tr class="<?php echo ($i%2==0)?"odd":"even";?>">
			<td>
				<span class="thmr_call">
					<?php echo $comprob["des"];?>
				</span>				
			</td>
			<td>
				<span class="thmr_call">
					<?php echo $comprob["serie"];?>
				</span>
			</td>
			<td>
				<span class="thmr_call">
					<?php echo $comprob["max"];?>
				</span>
			</td>
			<td>
				<span class="thmr_call">
					<?php echo $comprob["min"];?>
				</span>
				
			</td>
		</tr>
	<?php $i++;?>	
	<?php endforeach;?>
	<?php else:?>
		<tr class="odd">
			<td colspan="2">No hay items disponibles.</td>	
		</tr>
	<?php endif;?>	
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    '/categoria/paginator.phtml'); ?>
