<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es">
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <script type="text/javascript" src="/f/js/jquery-1.js"></script>
        <script type="text/javascript" src="/f/js/s3Slider.js"></script>
        <link href="/f/css/global.css" rel="stylesheet" type="text/css" media="all">
            <?php if ($this->slideshow) { ?>
                <link href="/f/css/banner.css" rel="stylesheet" type="text/css" media="all">
                <?php } ?>
<script type="text/javascript">
    $(document).ready(function() {
        $('#slider1').s3Slider({
            timeOut: 4000 
        });
    });
</script>
                </head>
                <body id="index">
                    <div id="page">
                        <!-- Header -->
                        <div id="header">
                            <div id="header-wrapper">
                                <!-- Logo -->
                                <div class="header-middle">
                                    <a id="header_logo" href="index.html" title="Delivery Premium">
                                        <img class="logo" src="img/logo.png" alt="Delivery Premium">
                                    </a>
                                    <div id="header_right">
                                        <!-- Block user information module HEADER -->
                                        <div id="header_user">
                                            <p id="header_user_info">
                                                Bienvenido,
                                                <a href="#">Entrar</a>
                                            </p>
                                            <ul id="header_nav">
                                                <li id="shopping_cart">
                                                    <a href="#" title="Su carrito de la compra"><span class="ajax_cart_quantity hidden">0</span>
                                                        <span class="ajax_cart_product_txt hidden">producto</span>
                                                        <span class="ajax_cart_product_txt_s hidden">productos</span>
                                                    </a>
                                                    <span class="ajax_cart_no_product">Sin productos</span>
                                                </li>
                                                <li id="your_account">
                                                    <a href="#" title="Su cuenta">Su cuenta</a>
                                                </li>
                                            </ul>
                                        </div>
                                        <!-- /Block user information module HEADER -->
                                        <div id="phone_block">
                                            <span>Central telefónica</span>
                                            <h4>721-2121</h4>
                                        </div>
                                        <div id="exchange_block">
                                            <p><a href="http://www.sunat.gob.pe/cl-at-ittipcam/tcS01Alias" target="_blank">Tipo de cambio</a></p>
                                        </div>
                                        <div id="social_block">
                                            <a href="#"><img src="img/faceb.png" alt="Facebook" title="Hazte fan en Facebook"></a>
                                        </div>
                                    </div>
                                    <div class="clear"></div>
                                </div>
                            </div>
                            <div id="menu-top">
                                <ul id="menu">
                                    <li><a href="/" class="<?php echo $this->menuActive1 ?>">Inicio</a></li>
                                    <li><a href="/zonas-reparto" class="<?php echo $this->menuActive2 ?>">Zonas de Reparto</a></li>	
                                    <li><a href="/realizar-pedido" class="<?php echo $this->menuActive3 ?>">Realizar Pedido</a></li>
                                    <li><a href="/politicas" class="<?php echo $this->menuActive4 ?>">Políticas</a></li>
                                    <li><a href="/contacto" class="<?php echo $this->menuActive5 ?>">Contacto</a></li>
                                </ul>
                                <!-- Block search module -->
                                <div id="search_block">
                                    <h4>Buscar</h4>
                                    <form method="get" action="/buscar" id="searchbox">
                                        <p class="block_content">
                                            <input class="search_query" id="search_query_block" name="search_query" value="Buscar" onfocus="if (this.value == 'Buscar') this.value = ''" onblur="if (this.value == '') this.value = 'Buscar'" type="text">
                                        </p>
                                    </form>
                                </div>	
                            </div>

                            <?php if ($this->slideshow) { ?>
                                <!-- Show slideshow in homepage -->
                                <div id="slideshow" >
                                    <div id="slider1">
                                        <ul id="slider1Content">
                                            <?php
                                            if (is_array($this->listaBanner)):
                                                foreach ($this->listaBanner as $index => $value):
                                                ?>
                                                    <li class="slider1Image">
                                                        <a href="<?php echo $value['url'] ?>">
                                                            <img src="../../imagen-banner/<?php echo $value['imagen'] ?>" alt="1" />
                                                        </a>
                                                        <span class="left">
                                                            <strong>
                                                                <?php echo $value['nombre'] ?>
                                                            </strong>
                                                            <br />
                                                                <?php echo $value['descripcion'] ?>
                                                        </span>
                                                    </li>
                                            <?php endforeach; endif; ?>
                                            <div class="clear slider1Image">
                                            </div>
                                        </ul>
                                    </div>
                                </div>
<?php } ?>

                        </div>
                        <div id="columns">
                            <!-- Left -->
                            <div id="left_column" class="column">
                                <!-- Block categories module -->
                                <div id="categories_block_left" class="block">
                                    <h4>Delivery de Productos</h4>
                                    <div class="block_content">
                                        <ul style="display: block;" class="tree dynamized">
<?php foreach ($this->listaCategoria as $index): ?>
    <?php if ($index['idpadre'] == '') { ?>
                                                    <li>
                                                        <a href="/productos/<?php echo $index['idcategoria']; ?>" title="<?php echo $index['nombre']; ?>"><?php echo $index['nombre']; ?></a>
                                                        <ul>
        <?php foreach ($this->listaCategoria as $index2): ?>
            <?php if ($index2['idpadre'] == $index['idcategoria']) { ?>
                                                                    <li>
                                                                        <a href="/productos/<?php echo $index2['idcategoria']; ?>" title="<?php echo $index2['nombre']; ?>"><?php echo $index2['nombre']; ?></a>
                                                                    </li>
            <?php } ?>
                                                    <?php endforeach; ?>
                                                        </ul>
                                                    </li>
    <?php } ?>
<?php endforeach; ?>
                                        </ul>
                                        <script type="text/javascript">
                                            // <![CDATA[
                                            // we hide the tree only if JavaScript is activated
                                            $('div#categories_block_left ul.dhtml').hide();
                                            // ]]>
                                        </script>
                                    </div>
                                </div>
                                <!-- /Block categories module -->
                                <!-- Block Newsletter module-->
                                <div id="newsletter_block_left" class="block">
                                    <h4>Suscríbete</h4>
                                    <div class="block_content">
                                        <form action="http://www.floreriadetalles.com/tienda/" method="post">
                                            <p>
                                                <input name="email" size="18" value="su email" onfocus="javascript:if(this.value=='su email')this.value='';" onblur="javascript:if(this.value=='')this.value='su email';" type="text">
                                            </p>
                                            <p>
                                                <select name="action">
                                                    <option selected="selected" value="0">suscribirse</option>
                                                    <option value="1">Borrarse</option>
                                                </select>
                                                <input value="ok" name="submitNewsletter" type="submit">
                                            </p>
                                        </form>
                                    </div>
                                </div>
                                <!-- /Block Newsletter module-->
                            </div>
                            <!-- Center -->
                            <div id="center_column">
                                <!-- MODULE Home Featured Products -->
<?php echo $this->layout()->content ?>
                                <!-- /MODULE Home Featured Products -->
                            </div>
                            <div id="right_column" class="column">
                                <!-- MODULE Block cart -->
                                <div id="cart_block" class="block exclusive">
                                    <h4>
                                        <a href="/realizar-pedido">Mi Carrito</a>
                                    </h4>
                                    <div class="block_content">
                                        <!-- block summary -->
                                        <div id="cart_block_summary" class="collapsed">
                                            <span class="ajax_cart_quantity" style="display:none;">0</span>
                                            <span class="ajax_cart_product_txt_s" style="display:none">productos</span>
                                            <span class="ajax_cart_product_txt">producto</span>
                                            <span class="ajax_cart_total" style="display:none">$0.00</span>
                                            <span class="ajax_cart_no_product">(vacío)</span>
                                        </div>
                                        <!-- block list of products -->
                                        <div id="cart_block_list" class="expanded">
                                            <?php
                                            $total = 0;
                                            if (count($this->listaArticuloCarrito) > 0) {
                                                ?>
                                                <dl class="products">

                                                    <?php
                                                    foreach ($this->listaArticuloCarrito as $index) {
                                                        ?>
                                                        <dt class="first_item" id="cart_block_product_<?php echo $index['idarticulo'] ?>">
                                                            <span class="quantity-formated"><span class="quantity"><?php echo $index['cantidadArticulo'] ?></span>x</span>
                                                            <a title="Rosa 1" href="/detalle-producto/<?php echo $index['idarticulo'] ?>" class="cart_block_product_name">
        <?php echo $index['nombre'] ?></a>
                                                            <span class="remove_link"><a title="eliminar este producto de mi carrito" href="/realizar-pedido/eliminar-carrito/idArticulo/<?php echo $index['idarticulo'] ?>" 
                                                                                         class="ajax_cart_block_remove_link" rel="nofollow">&nbsp;</a></span>
                                                            <span class="price">S/. <?php echo $index['precioventa'] ?></span>
                                                        </dt>
                                                        <?php
                                                        $total = $total + $index['precioventa'] * $index['cantidadArticulo'];
                                                    }
                                                    ?>
                                                </dl>
                                            <?php } else { ?>
                                                <p id="cart_block_no_products">Sin producto</p>
<?php } ?>    
                                            <div id="cart-prices">
                                                <div id="cart-prices-box">
                                                    <span>Transporte</span>
                                                    <span id="cart_block_shipping_cost" class="price ajax_cart_shipping_cost">$0.00</span>
                                                </div>
                                                <div id="cart-prices-box">
                                                    <span>Total</span>
                                                    <span id="cart_block_total" class="price ajax_block_cart_total">S/. <?php echo $total; ?></span>
                                                </div>
                                            </div>
                                            <p id="cart-buttons">
                                                <a href="http://www.floreriadetalles.com/tienda/order.php" class="button_blockcart" title="Carrito">Carrito</a>			<a href="http://www.floreriadetalles.com/tienda/order.php?step=1" id="button_order_cart" class="button_blockcart " title="Confirmar">Confirmar</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <!-- /MODULE Block cart -->
                                <!-- MODULE Block specials -->
                                <!--                    <div id="special_block_right" class="block products_block exclusive blockspecials">
                                                        <h4><a href="#" title="Ofertas">Oferta Reciente</a></h4>
                                                        <div class="block_content">
                                                            <h5><a href="#" title="Variados 4">Variados 4</a></h5>
                                                            <p class="description">&nbsp;bouquet de rosas rojas y...</p>
                                                            <div class="product_image">
                                                                <a href="#"><img src="delivery_files/39-92-large.jpg" alt="Variados 4" title="Variados 4"></a>
                                                            </div>
                                                            <span class="price-discount">Antes $43.00</span>
                                                            <span class="price">$32.00</span>
                                                            <a class="special-addcart ajax_add_to_cart_button" rel="ajax_id_product_39" href="#" title="Add to cart">Agregar a carrito</a>
                                                            <p>
                                                                <a href="#" title="Ver todas las ofertas" class="button_large">Ver todas las ofertas</a>
                                                            </p>
                                                        </div>
                                                    </div>-->
                                <!-- /MODULE Block specials -->
                                <!--                    <div class="box-gray">
                                                        <h4>Se aceptan tarjetas</h4>
                                                        <a href="http://www.floreriadetalles.com/tienda/"><img src="img/payment001.png"></a>
                                                    </div>-->
                            </div>
                            <div class="clear"></div>
                        </div>
                        <!-- Footer -->
                        <div id="footer">
                            <div id="footer_top">
                                <div class="info">
                                    SERVICIO DE REPARTO EXCLUSIVO.<br />
                                    <span style="color:#FFF; font-size:15px">Atención de repartos de Jueves a Domingo de 5pm a 5am, Feriados de 3pm. a 3am.</span><br /><br />
                                    TOMAR BEBIDAS ALCOHÓLICAS EN EXCESO ES DAÑINO
                                </div>
                                <div class="logo">
                                    <a href="#"><img src="img/logo_footer.png"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </body>
                </html>