<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" xmlns:fb="http://ogp.me/ns/fb#">
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <meta property="og:title" content="delivery premium" />
        <meta property="og:type" content="author" />
        <meta property="og:url" content="http://deliverypremiumsac.com" />
        <meta property="og:image" content="http://deliverypremiumsac.com/f/img/logo.png" />
        <meta property="og:site_name" content="delivery premium" />
        <meta property="fb:admins" content="698823485" />
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <link href="/f/css/updateBrowser.css" rel="stylesheet" type="text/css" media="all">
       <script type="text/javascript" src="/f/js/jquery-1.js"></script>
       <script type="text/javascript" src="/f/js/jquery.easing.1.3.js"></script>
       <script type="text/javascript" src="/f/js/jquery.roundabout.js"></script>
            

    </head>
    <body id="index">
        
        <!-- MODULE Home Featured Products -->
        <?php echo $this->layout()->content ?>
        <!-- /MODULE Home Featured Products -->
    </body>
</html>