<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" xmlns:fb="http://ogp.me/ns/fb#">
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <link href="/f/css/updateBrowser.css" rel="stylesheet" type="text/css" media="all">
    </head>
    <body id="index">
        <!-- MODULE Home Featured Products -->
        <?php echo $this->layout()->content ?>
        <!-- /MODULE Home Featured Products -->
    </body>
</html>