<!--<div id="maq_alineacion2">
            <div id="maq_principal">
          <div class="web_interna web_modo2" id="internaTipo1">
                	<h2 class="titulo">Productos</h2>
                    <div id="web_columna1">
                        
                        <ul class="web_menuLateral">
                        <?php foreach($this->categorias as $index){ ?>    
                            <li><a href="/productos/<?php echo $index['idcategoria']?>"><?php echo $index['nombre']?></a></li>
                        <?php } ?>    
                        </ul>
                    </div>
                    <div id="web_columna2">
                    	<h3 class="subtitulo">Cocina</h3>
                        <div class="listado" id="listadoTipo1">
                        	<ul>
                            	<?php foreach($this->articulos as $index){?>
                                    <li>
                                	<div class="bloque">
                                        <img src="images/<?php echo $index['images']?>" width="150" height="120" />
                                        <div class="info">
                                            <h3><?php echo $index['nombre']?></h3>
                                            <p>Precio: S/.<?php echo $index['precioventa']?></p>
                                            <a href="/detalle-producto/<?php echo $index['idarticulo']?>" class="boton"><span><strong>Ver detalle</strong></span></a>
                                        </div>
                                    </div>
                                </li>
                                <?php }?>
                                
                                
                                
                            </ul><br />
                        </div>
                    </div><br />
                </div>
            </div>
        </div>-->
<div id="featured-products_block_center" class="block products_block">
    <h4>Productos destacados</h4>
    <div class="block_content">
        <?php
        $params = array('idsubcategoria'=>$this->idsubcategoria);
        echo $paginator = $this->paginationControl($this->articulos,
                                    'Sliding',
                                    '/productos/paginator.phtml',$params); 
        ?>
        <?php if(count($this->articulos)>0){?>
        <ul>
                        <?php foreach($this->articulos as $index): ?>
            <li class="ajax_block_product first_item clear ">
                <div id="product-box">
                    <h5>
                        <a href="#" title="<?php echo $index['nombre']?>"><?php echo $index['nombre']?></a>
                    </h5>
                    <div class="product_imagebox">
                        <a href="#" title="<?php echo $index['nombre']?>" class="product_image">
                            <img src="/imagen-articulo/<?php echo $index['imagen']?>" alt="<?php echo $index['nombre']?>" >
                        </a>
                    </div>
                    <div>
                        <p class="price_container" style="width: 100px; ">
                            <span class="price"><?php echo $index['precioventa']?></span>
                        </p>
                        <p class="price_container" style="width: 70px;">
                        <input type="text" style="width: 30px; height: 20px;">
                        <span>cantidad</span>
                        </p>
                        <p class="product_buttons">
                            
                            <a class="product-addcart ajax_add_to_cart_button" rel="ajax_id_product_14" href="" title="Añadir al carrito">Añadir al carrito</a>
                            <a class="product-viewdetails" href="/detalle-producto/<?php echo $index['idarticulo']?>" title="Ver">Ver</a>
                        </p>					
                    </div>						
                </div>
            </li>
            <?php  endforeach; ?>

        </ul>
        <?php echo $paginator;?>
    <?php  } else { ?>    
        No se encontro ningun articulo
    <?php  } ?>    
    </div>
</div>