<table class="sticky-enabled tableSelect-processed sticky-table">
    <caption><a href="/nuevo-banner">Nuevo Banner </a></caption>
    <thead class="tableHeader-processed">
        <tr>
            <th class="select-all"><input type="checkbox" class="form-checkbox" title="Select all rows in this table"></th>
            <th>Título</th>
            <th>Descripcion</th>
            <th>Imagen</th>
            <th>Gestionar</th>
            
        </tr>
    </thead>
    <tbody>    
        <?php if(is_array($this->listaBanner)):
                foreach($this->listaBanner as $index => $value ):        
        ?>
        <tr>
            <td><?php echo $index?></td>
            <td><?php echo $value['nombre'] ?></td>
            <td><?php echo $value['descripcion'] ?></td>
            <td><img src='../../imagen-banner/<?php echo $value['imagen'] ?>' width="48" height="24" title="<?php echo $value['imagen']?>"/></td>
            <td>
                <a href="/admin/admin-web/editar-banner/idBanner/<?php echo $value['idbanner']?>">
                    <img src="../../f/img/edit.png" title="Editar Banner" alt="Editar" border="0" />
                </a>
                &nbsp;
                <a href="/admin/admin-web/eliminar-banner/idBanner/<?php echo $value['idbanner']?>">
                    <img src="../../f/img/borrar.png" title="Borrar Banner" alt="Eliminar" border="0" />
                </a>
                &nbsp
            </td>
        </tr>
        <?php endforeach; endif; ?>
   </tbody>
</table>
<br />

